<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="it_IT" sourcelanguage="it">
<context>
    <name>CreateRelation</name>
    <message>
        <location filename="create_relation.py" line="185"/>
        <source>&amp;Create Relation</source>
        <translatorcomment>Crea Relazioni</translatorcomment>
        <translation>Crea Relazioni</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="172"/>
        <source>Create Relation</source>
        <translatorcomment>Crea Relazioni</translatorcomment>
        <translation>Crea Relazioni</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="257"/>
        <source>❌️ Errore: selezionare entrambi i layer e i campi.</source>
        <translatorcomment>❌️ Errore: selezionare entrambi i layer e i campi.</translatorcomment>
        <translation>❌️ Errore: selezionare entrambi i layer e i campi.</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="261"/>
        <source>❌ Errore: i layer selezionati devono essere di tipo vettoriale.</source>
        <translatorcomment>❌ Errore: i layer selezionati devono essere di tipo vettoriale.</translatorcomment>
        <translation>❌ Errore: i layer selezionati devono essere di tipo vettoriale.</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="266"/>
        <source>❌ Errore: il manager delle relazioni non è disponibile.</source>
        <translatorcomment>❌ Errore: il manager delle relazioni non è disponibile.</translatorcomment>
        <translation>❌ Errore: il manager delle relazioni non è disponibile.</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="269"/>
        <source>uno-a-uno</source>
        <translatorcomment>uno-a-uno</translatorcomment>
        <translation>uno-a-uno</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="274"/>
        <source>Join già esistente</source>
        <translatorcomment>Join già esistente</translatorcomment>
        <translation>Join già esistente</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="274"/>
        <source>⚠️ Esiste già un join tra questi layer con gli stessi campi.
Vuoi procedere comunque?</source>
        <translatorcomment>⚠️ Esiste già un join tra questi layer con gli stessi campi.\nVuoi procedere comunque?</translatorcomment>
        <translation>⚠️ Esiste già un join tra questi layer con gli stessi campi.\nVuoi procedere comunque?</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="282"/>
        <source>ℹ️ Operazione annullata: il join esisteva già.</source>
        <translatorcomment>ℹ️ Operazione annullata: il join esisteva già.</translatorcomment>
        <translation>ℹ️ Operazione annullata: il join esisteva già.</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="285"/>
        <source>ℹ️ Procedo nonostante il join esistente.</source>
        <translatorcomment>ℹ️ Procedo nonostante il join esistente.</translatorcomment>
        <translation>ℹ️ Procedo nonostante il join esistente.</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="294"/>
        <source>✔️ Join creato con successo tra {layer1.name()} e {layer2.name()} usando i campi {field1} → {field2}.</source>
        <translatorcomment>✔️ Join creato con successo tra {layer1.name()} e {layer2.name()} usando i campi {field1} → {field2}.</translatorcomment>
        <translation>✔️ Join creato con successo tra {layer1.name()} e {layer2.name()} usando i campi {field1} → {field2}.</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="297"/>
        <source>molti-a-molti</source>
        <translatorcomment>molti-a-molti</translatorcomment>
        <translation>molti-a-molti</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="389"/>
        <source>Relazione già esistente</source>
        <translatorcomment>Relazione già esistente</translatorcomment>
        <translation>Relazione già esistente</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="301"/>
        <source>⚠️ Esistono già relazioni tra questi layer.
Vuoi procedere comunque?</source>
        <translatorcomment>⚠️ Esistono già relazioni tra questi layer.\nVuoi procedere comunque?</translatorcomment>
        <translation>⚠️ Esistono già relazioni tra questi layer.\nVuoi procedere comunque?</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="309"/>
        <source>ℹ️ Operazione annullata: relazione già esistente.</source>
        <translatorcomment>ℹ️ Operazione annullata: relazione già esistente.</translatorcomment>
        <translation>ℹ️ Operazione annullata: relazione già esistente.</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="312"/>
        <source>ℹ️ Procedo nonostante la relazione esistente.</source>
        <translatorcomment>ℹ️ Procedo nonostante la relazione esistente.</translatorcomment>
        <translation>ℹ️ Procedo nonostante la relazione esistente.</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="357"/>
        <source>Salva la tabella ponte</source>
        <translatorcomment>Salva la tabella ponte</translatorcomment>
        <translation>Salva la tabella ponte</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="374"/>
        <source>✔️ Tabella ponte salvata su disco: {file_path}</source>
        <translatorcomment>✔️ Tabella ponte salvata su disco: {file_path}</translatorcomment>
        <translation>✔️ Tabella ponte salvata su disco: {file_path}</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="376"/>
        <source>❌ Errore nel salvataggio della tabella ponte su disco.</source>
        <translatorcomment>❌ Errore nel salvataggio della tabella ponte su disco.</translatorcomment>
        <translation>❌ Errore nel salvataggio della tabella ponte su disco.</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="379"/>
        <source>✔ Relazioni molti-a-molti create correttamente tra &apos;{layer1.name()}&apos; e &apos;{layer2.name()}&apos; tramite la tabella &apos;{ponte_layer.name()}&apos;.</source>
        <translatorcomment>✔ Relazioni molti-a-molti create correttamente tra &apos;{layer1.name()}&apos; e &apos;{layer2.name()}&apos; tramite la tabella &apos;{ponte_layer.name()}&apos;.</translatorcomment>
        <translation>✔ Relazioni molti-a-molti create correttamente tra &apos;{layer1.name()}&apos; e &apos;{layer2.name()}&apos; tramite la tabella &apos;{ponte_layer.name()}&apos;.</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="381"/>
        <source>✅ Le relazioni molti-a-molti sembrano funzionare, ma si è verificato un problema nell&apos;aggiunta formale delle relazioni al progetto.</source>
        <translatorcomment>✅ Le relazioni molti-a-molti sembrano funzionare, ma si è verificato un problema nell&apos;aggiunta formale delle relazioni al progetto.</translatorcomment>
        <translation>✅ Le relazioni molti-a-molti sembrano funzionare, ma si è verificato un problema nell&apos;aggiunta formale delle relazioni al progetto.</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="389"/>
        <source>⚠️ Esiste già una relazione con gli stessi parametri.
Vuoi procedere comunque?</source>
        <translatorcomment>⚠️ Esiste già una relazione con gli stessi parametri.\nVuoi procedere comunque?</translatorcomment>
        <translation>⚠️ Esiste già una relazione con gli stessi parametri.\nVuoi procedere comunque?</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="397"/>
        <source>ℹ️ Operazione annullata: relazione già presente.</source>
        <translatorcomment>ℹ️ Operazione annullata: relazione già presente.</translatorcomment>
        <translation>ℹ️ Operazione annullata: relazione già presente.</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="400"/>
        <source>ℹ️ Procedo nonostante la relazione già presente.</source>
        <translatorcomment>ℹ️ Procedo nonostante la relazione già presente.</translatorcomment>
        <translation>ℹ️ Procedo nonostante la relazione già presente.</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="413"/>
        <source>❌ Errore: i campi specificati non esistono nei layer selezionati.</source>
        <translatorcomment>❌ Errore: i campi specificati non esistono nei layer selezionati.</translatorcomment>
        <translation>❌ Errore: i campi specificati non esistono nei layer selezionati.</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="419"/>
        <source>❌ Errore: la relazione creata non è valida. Controlla i layer e i campi.</source>
        <translatorcomment>❌ Errore: la relazione creata non è valida. Controlla i layer e i campi.</translatorcomment>
        <translation>❌ Errore: la relazione creata non è valida. Controlla i layer e i campi.</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="423"/>
        <source>✔ Relazione {relation_type} creata con successo.</source>
        <translatorcomment>✔ Relazione {relation_type} creata con successo.</translatorcomment>
        <translation>✔ Relazione {relation_type} creata con successo.</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="426"/>
        <source>✅ Relazione creata correttamente, ma addRelation() ha restituito False.</source>
        <translatorcomment>✅ Relazione creata correttamente, ma addRelation() ha restituito Falso.</translatorcomment>
        <translation>✅ Relazione creata correttamente, ma addRelation() ha restituito Falso.</translation>
    </message>
    <message>
        <location filename="create_relation.py" line="428"/>
        <source>❌ Errore nella creazione della relazione.</source>
        <translatorcomment>❌ Errore nella creazione della relazione.</translatorcomment>
        <translation>❌ Errore nella creazione della relazione.</translation>
    </message>
</context>
<context>
    <name>CreateRelationDialogBase</name>
    <message>
        <location filename="create_relation_dialog_base.ui" line="14"/>
        <source>Create Relation</source>
        <translatorcomment>Crea Relazioni</translatorcomment>
        <translation>Crea Relazioni</translation>
    </message>
    <message>
        <location filename="create_relation_dialog_base.ui" line="26"/>
        <source>Crea relazione</source>
        <translatorcomment>Crea Relazioni</translatorcomment>
        <translation>Crea Relazioni</translation>
    </message>
    <message>
        <location filename="create_relation_dialog_base.ui" line="52"/>
        <source>Log:</source>
        <translatorcomment>Log:</translatorcomment>
        <translation>Log:</translation>
    </message>
    <message>
        <location filename="create_relation_dialog_base.ui" line="65"/>
        <source>Chiudi</source>
        <translatorcomment>Chiudi</translatorcomment>
        <translation>Chiudi</translation>
    </message>
    <message>
        <location filename="create_relation_dialog_base.ui" line="78"/>
        <source>Salva relazione N-M</source>
        <translatorcomment>Salva relazione N-M</translatorcomment>
        <translation>Salva relazione N-M</translation>
    </message>
    <message>
        <location filename="create_relation_dialog_base.ui" line="91"/>
        <source>Tabella padre</source>
        <translatorcomment>Tabella padre</translatorcomment>
        <translation>Tabella padre</translation>
    </message>
    <message>
        <location filename="create_relation_dialog_base.ui" line="172"/>
        <source>Campo</source>
        <translatorcomment>Campo</translatorcomment>
        <translation>Campo</translation>
    </message>
    <message>
        <location filename="create_relation_dialog_base.ui" line="185"/>
        <source>Layer</source>
        <translatorcomment>Layer</translatorcomment>
        <translation>Layer</translation>
    </message>
    <message>
        <location filename="create_relation_dialog_base.ui" line="150"/>
        <source>Tabella figlio</source>
        <translatorcomment>Tabella figlio</translatorcomment>
        <translation>Tabella figlio</translation>
    </message>
    <message>
        <location filename="create_relation_dialog_base.ui" line="209"/>
        <source>Relazione</source>
        <translatorcomment>Relazione</translatorcomment>
        <translation>Relazione</translation>
    </message>
    <message>
        <location filename="create_relation_dialog_base.ui" line="222"/>
        <source>uno-a-uno</source>
        <translatorcomment>uno-a-uno</translatorcomment>
        <translation>uno-a-uno</translation>
    </message>
    <message>
        <location filename="create_relation_dialog_base.ui" line="227"/>
        <source>uno-a-molti</source>
        <translatorcomment>uno-a-molti</translatorcomment>
        <translation>uno-a-molti</translation>
    </message>
    <message>
        <location filename="create_relation_dialog_base.ui" line="232"/>
        <source>molti-a-molti</source>
        <translatorcomment>molti-a-molti</translatorcomment>
        <translation>molti-a-molti</translation>
    </message>
    <message>
        <location filename="create_relation_dialog_base.ui" line="247"/>
        <source>Nome relazione ponte per N-M</source>
        <translatorcomment>Nome relazione ponte per N-M</translatorcomment>
        <translation>Nome relazione ponte per N-M</translation>
    </message>
</context>
</TS>
